export { default as Movies } from './Movies'
export { default as Navbar } from './Navbar'
export { default as Trends } from './Trends'
export { default as TvShows } from './TvShows'
export { default as pricing } from './Pricing'